# 1) Node 빌드 스테이지
FROM node:18 AS builder

# 빌드 아규먼트 선언
ARG REACT_APP_IMP_CHANNEL_KEY
ARG REACT_APP_NICE_CHANNEL_KEY
ARG REACT_APP_PORTONE_CHANNEL_KEY
ARG REACT_APP_INICIS_CHANNEL_KEY
ARG REACT_APP_IMP_STOREID

# ENV 로 설정 (CRA는 REACT_APP_ 접두어로 시작하는 변수를 build 시점에 인식)
ENV REACT_APP_IMP_CHANNEL_KEY=$REACT_APP_IMP_CHANNEL_KEY
ENV REACT_APP_NICE_CHANNEL_KEY=$REACT_APP_NICE_CHANNEL_KEY
ENV REACT_APP_PORTONE_CHANNEL_KEY=$REACT_APP_PORTONE_CHANNEL_KEY
ENV REACT_APP_INICIS_CHANNEL_KEY=$REACT_APP_INICIS_CHANNEL_KEY
ENV REACT_APP_IMP_STOREID=$REACT_APP_IMP_STOREID

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./

RUN npm run build

FROM nginx:alpine

# 1) 빌드 결과물을 복사
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY my-react.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]